# See https://pre-commit.com for more information
default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: debug-statements
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
    -   id: mypy
        additional_dependencies:
        - pydantic>=2.5.3
        - sqlalchemy[mypy]>=2.0.25
        - types-python-jose>=3.3.4
        - types-passlib>=1.7.7
        - types-aiofiles>=23.2.0
        - types-requests>=2.31.0
        - types-setuptools>=69.0.0
        - types-python-dateutil>=2.8.19
        - prometheus_client>=0.19.0

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

-   repo: local
    hooks:
    -   id: poetry-check
        name: poetry check
        entry: poetry check
        language: system
        pass_filenames: false
        always_run: true

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
    -   id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
