# See https://pre-commit.com for more information
default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: debug-statements
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: local
    hooks:
    -   id: ruff-check
        name: ruff check
        entry: poetry run ruff check
        language: system
        types: [python]
        require_serial: true

    -   id: ruff-format
        name: ruff format
        entry: poetry run ruff format
        language: system
        types: [python]
        require_serial: true

    -   id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        require_serial: true

    -   id: bandit
        name: bandit
        entry: poetry run bandit
        language: system
        types: [python]
        args: ["-c", "pyproject.toml"]
        require_serial: true

    -   id: poetry-check
        name: poetry check
        entry: poetry check
        language: system
        pass_filenames: false
        always_run: true

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
    -   id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
